# Generate tower-accent.css — fetches the CN Tower's current light colour
# for the blog accent, or falls back to #1e9bff if the API is unreachable.
param(
  [string]$OutDir = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
)

$Fallback = "#1e9bff"
$OutFile = Join-Path $OutDir "static" "tower-accent.css"
$Sources = @(
  "https://tower-lights.herokuapp.com/scheduleComplete",
  "https://raw.githubusercontent.com/alexbelloni/cntowerlightsapi/master/routes/fakeDataFromCNTower.json",
  "https://raw.githubusercontent.com/alexbelloni/cntowerlightsapi/master/routes/fakeDataFromAPI.json"
)

function Get-Colour($Value, $Depth = 0) {
  if ($Depth -gt 10) { return $null }
  if ($Value -is [string]) {
    $m = [regex]::Match($Value, '#[0-9a-f]{6}', 'IgnoreCase')
    if ($m.Success) { return $m.Value }
    return $null
  }
  if ($Value -is [hashtable] -or $Value -is [pscustomobject]) {
    $PriorityKeys = @('colourCaption', 'colorCaption', 'colour', 'color', 'colours', 'colors')
    foreach ($key in $PriorityKeys) {
      if ($null -ne $Value.$key) {
        $c = Get-Colour $Value.$key ($Depth + 1)
        if ($c) { return $c }
      }
    }
    foreach ($v in $Value.PSObject.Properties.Value) {
      $c = Get-Colour $v ($Depth + 1)
      if ($c) { return $c }
    }
  }
  return $null
}

$Accent = $null
foreach ($Source in $Sources) {
  try {
    $Raw = Invoke-RestMethod -Uri $Source -TimeoutSec 4 -ErrorAction Stop
    $Accent = Get-Colour $Raw
    if ($Accent) { break }
  } catch { continue }
}

if (-not $Accent) { $Accent = $Fallback }

$Css = "/* Tower accent colour — generated by Generate-TowerAccent.ps1 */`n:root { --accent: $Accent; }`n"
Set-Content -Path $OutFile -Value $Css -Encoding utf8NoBOM -NoNewline
Write-Host "tower-accent.css -> $Accent"
